name: Lint

on: [push, pull_request]

jobs:
  inspect-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare to install
      run: sudo apt-get update
    - name: python for cpplint
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: install tools
      run: |
        pip install cpplint
        sudo apt-get install -y clang-tidy
        sudo apt-get install -y cppcheck

    - name: cpplint
      run: |
        cpplint  --filter=-legal --linelength=150 *.cpp *.h

    - name: cppcheck
      run: |
        cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem --std=c++17 *.cpp *.h

    - name: clang-tidy check
      run: |
        # Create a compile commands database for clang-tidy
        echo '[{"directory": ".", "command": "g++ -std=c++17 -I. main.cpp test_payment_mode.cpp", "file": "main.cpp"}, {"directory": ".", "command": "g++ -std=c++17 -I. test_payment_mode.cpp main.cpp", "file": "test_payment_mode.cpp"}]' > compile_commands.json
        clang-tidy main.cpp test_payment_mode.cpp -- -std=c++17 -I.
