name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ cmake

    - name: configure with cmake
      run: |
        mkdir build
        cd build
        cmake ..
      
    - name: build project
      run: |
        cd build
        cmake --build .
      
    - name: run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: verify build artifacts
      run: |
        echo "Build completed successfully"
        ls -la build/
